version: '2'
services:

  # The Application
  app:
    build: .
    volumes:
      - ./:/usr/src/app
    volumes_from:
      - yarn-cache
    ports:
      - 8080:8080

  yarn-cache:
    image: busybox
    volumes:
      - /root/.yarn-cache